### ISSUE TITLE
Master Kings Fall

### ISSUE THREAD

**Issue by ctrlcmdshft** [sbrocket/failsafe#25]
As per bungie the Master version of Kings Fall will be available Sept 20th. Wondering if possible to add Master versions to bot for the Raids

**Comment by sbrocket** [comment]
Master is just the difficulty setting for the raid. Usually we'd handle that just by putting that information in the title and/or the description of the event, rather than creating a whole separate event type. More event types than necessary would clutter up the selection list when creating new events.
