### ISSUE TITLE
Event edit response doesn’t say what was changed

### ISSUE THREAD

**Issue by fizzlepuppy** [sbrocket/failsafe#4]
After /lfg edit recur on an event, the response didn’t say the event was set to recur weekly. The response should confirm the user’s action as having happened. Perhaps an event summary is useful but a string that says what changed would be enough

**Comment by sbrocket** [comment]
An event summary like the current event embed, or something else? I considered the former but didn’t want to generate indefinite amounts of embeds for the bot to keep up to date, and they’re big. Maybe a text summary of the event and the before/after…

**Comment by fizzlepuppy** [comment]
If there was a way to do private embeds that would work. Text summary would
be helpful. Should probably at least give you the join code?

**Comment by sbrocket** [comment]
There can be private embeds yeah, like the one after initial event creation…the problem is they can only be edited for 15 minutes because after that the interaction token expires, so I make sure to delete them before that so they aren’t stale. But they’d be visible for 15 mins at least, and I can leave a short text description behind.
